using CoinFill.Helpers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoinFill.Helpers.Providers
{
    public static class SupportedCountriesProvider
    {
        public static List<Country> SupportedCountries { get; } = new List<Country>
        {
            new Country { Name = "United States of America", Icon = "US" },
            new Country { Name = "Austria", Icon = "AT" },
            new Country { Name = "Australia", Icon = "AU" },
            new Country { Name = "Belgium", Icon = "BE" },
            new Country { Name = "Poland", Icon = "PL" },
            new Country { Name = "Portugal", Icon = "PT" },
            new Country { Name = "Brazil", Icon = "BR" },
            new Country { Name = "Bulgaria", Icon = "BG" },
            new Country { Name = "Bosnia and Herzegovina", Icon = "BA" },
            new Country { Name = "Belarus", Icon = "BY" },
            new Country { Name = "Bahrain", Icon = "BH" },
            new Country { Name = "Croatia", Icon = "HR" },
            new Country { Name = "Cyprus", Icon = "CY" },
            new Country { Name = "Czechia", Icon = "CZ" },
            new Country { Name = "Denmark", Icon = "DK" },
            new Country { Name = "Ukraine", Icon = "UA" },
            new Country { Name = "United Arab Emirates", Icon = "AE" },
                new Country { Name = "China", Icon = "CN" },
                new Country { Name = "Canada", Icon = "CA" },
                new Country { Name = "Georgia", Icon = "GE" },
                new Country { Name = "Germany", Icon = "DE" },
                new Country { Name = "Saudi Arabia", Icon = "SA" },
                new Country { Name = "Senegal", Icon = "SN" },
                new Country { Name = "Serbia", Icon = "RS" },
                new Country { Name = "Argentina", Icon = "AR" },
                new Country { Name = "Armenia", Icon = "AM" },
                new Country { Name = "Qatar", Icon = "QA" },
                new Country { Name = "North Macedonia", Icon = "MK" },
                new Country { Name = "Romania", Icon = "RO" },
                new Country { Name = "Russian Federation", Icon = "RU" },
                new Country { Name = "Azerbaijan", Icon = "AZ" },
                new Country { Name = "Singapore", Icon = "SG" },
                new Country { Name = "Slovakia", Icon = "SK" },
                new Country { Name = "Slovenia", Icon = "SI" },
                new Country { Name = "Finland", Icon = "FI" },
                new Country { Name = "France", Icon = "FR" },
                new Country { Name = "Estonia", Icon = "EE" },
                new Country { Name = "Albania", Icon = "AL" },
                new Country { Name = "Tunisia", Icon = "TN" },
                new Country { Name = "Turkey", Icon = "TR" },
                new Country { Name = "Hong Kong", Icon = "HK" },
                new Country { Name = "Hungary", Icon = "HU" },
                new Country { Name = "Iceland", Icon = "IS" },
                new Country { Name = "India", Icon = "IN" },
                new Country { Name = "Indonesia", Icon = "ID" },
                new Country { Name = "New Zealand", Icon = "NZ" },
                new Country { Name = "Iran", Icon = "IR" },
                new Country { Name = "Iraq", Icon = "IQ" },
                new Country { Name = "Ireland", Icon = "IE" },
                new Country { Name = "Netherlands", Icon = "NL" },
                new Country { Name = "Japan", Icon = "JP" },
                new Country { Name = "Gibraltar", Icon = "GI" },
                new Country { Name = "Greece", Icon = "GR" },
                new Country { Name = "Greenland", Icon = "GL" },
                new Country { Name = "Nigeria", Icon = "NG" },
                new Country { Name = "Sweden", Icon = "SE" },
                new Country { Name = "Switzerland", Icon = "CH" },
                new Country { Name = "Taiwan", Icon = "TW" },
                new Country { Name = "Tajikistan", Icon = "TJ" },
                new Country { Name = "Norway", Icon = "NO" },
                new Country { Name = "Oman", Icon = "OM" },
                new Country { Name = "Pakistan", Icon = "PK" },
                new Country { Name = "Liechtenstein", Icon = "LI" },
                new Country { Name = "Lithuania", Icon = "LT" },
                new Country { Name = "Luxembourg", Icon = "LU" },
                new Country { Name = "Israel", Icon = "IL" },
                new Country { Name = "Italy", Icon = "IT" },
                new Country { Name = "Algeria", Icon = "DZ" },
                new Country { Name = "Andorra", Icon = "AD" },
                new Country { Name = "Angola", Icon = "AO" },
                new Country { Name = "Anguilla", Icon = "AI" },
                new Country { Name = "Bahamas ", Icon = "BS" },
                new Country { Name = "Bangladesh", Icon = "BD" },
                new Country { Name = "Barbados", Icon = "BB" },
                new Country { Name = "Belize", Icon = "BZ" },
                new Country { Name = "Benin", Icon = "BJ" },
                new Country { Name = "Bermuda", Icon = "BM" },
                new Country { Name = "Bolivia", Icon = "BO" },
                new Country { Name = "Botswana", Icon = "BW" },
                new Country { Name = "Burkina Faso", Icon = "BF" },
                new Country { Name = "Cambodia", Icon = "KH" },
                new Country { Name = "Cameroon", Icon = "CM" },
                new Country { Name = "Cayman Islands", Icon = "KY" },
                new Country { Name = "Central African Republic", Icon = "CF" },
                new Country { Name = "Chile", Icon = "CL" },
                new Country { Name = "Colombia", Icon = "CO" },
                new Country { Name = "Comoros", Icon = "KM" },
                new Country { Name = "Congo", Icon = "CD" },
                new Country { Name = "Costa Rica", Icon = "CR" },
                new Country { Name = "Cuba", Icon = "CU" },
                new Country { Name = "Djibouti", Icon = "DJ" },
                new Country { Name = "Dominican Republic", Icon = "DO" },
                new Country { Name = "Ecuador", Icon = "EC" },
                new Country { Name = "Egypt", Icon = "EG" },
                new Country { Name = "El Salvador", Icon = "SV" },
                new Country { Name = "Equatorial Guinea", Icon = "GQ" },
                new Country { Name = "Eritrea", Icon = "ER" },
                new Country { Name = "Eswatini", Icon = "SZ" },
                new Country { Name = "Ethiopia", Icon = "ET" },
                new Country { Name = "Gabon", Icon = "GA" },
                new Country { Name = "Gambia", Icon = "GM" },
                new Country { Name = "Ghana", Icon = "GH" },
                new Country { Name = "Guinea", Icon = "GN" },
                new Country { Name = "Haiti", Icon = "HT" },
                new Country { Name = "Honduras", Icon = "HN" },
                new Country { Name = "Isle of Man", Icon = "IM" },
                new Country { Name = "Jamaica", Icon = "JM" },
                new Country { Name = "Jersey", Icon = "JE" },
                new Country { Name = "Jordan", Icon = "JO" },
                new Country { Name = "Kazakhstan", Icon = "KZ" },
                new Country { Name = "Kenya", Icon = "KE" },
                new Country { Name = "South Korea", Icon = "KR" },
                new Country { Name = "Kuwait", Icon = "KW" },
                new Country { Name = "Kyrgyzstan", Icon = "KG" },
                new Country { Name = "Laos", Icon = "LA" },
                new Country { Name = "Latvia", Icon = "LV" },
                new Country { Name = "Lebanon", Icon = "LB" },
                new Country { Name = "Lesotho", Icon = "LS" },
                new Country { Name = "Liberia", Icon = "LR" },
                new Country { Name = "Libya", Icon = "LY" },
                new Country { Name = "Macao", Icon = "MO" },
                new Country { Name = "Madagascar", Icon = "MG" },
                new Country { Name = "Malawi", Icon = "MW" },
                new Country { Name = "Malaysia", Icon = "MY" },
                new Country { Name = "Maldives", Icon = "MV" },
                new Country { Name = "Mali", Icon = "ML" },
                new Country { Name = "Malta", Icon = "MT" },
                new Country { Name = "Mauritius", Icon = "MU" },
                new Country { Name = "Mexico", Icon = "MX" },
                new Country { Name = "Moldova", Icon = "MD" },
                new Country { Name = "Monaco", Icon = "MC" },
                new Country { Name = "Mongolia", Icon = "MN" },
                new Country { Name = "Montenegro", Icon = "ME" },
                new Country { Name = "Morocco", Icon = "MA" },
                new Country { Name = "Mozambique", Icon = "MZ" },
                new Country { Name = "Myanmar", Icon = "MM" },
                new Country { Name = "Namibia", Icon = "NA" },
                new Country { Name = "Nepal", Icon = "NP" },
                new Country { Name = "New Caledonia", Icon = "NC" },
                new Country { Name = "Nicaragua", Icon = "NI" },
                new Country { Name = "Niger", Icon = "NE" },
                new Country { Name = "Panama", Icon = "PA" },
                new Country { Name = "Papua New Guinea", Icon = "PG" },
                new Country { Name = "Paraguay", Icon = "PY" },
                new Country { Name = "Peru", Icon = "PE" },
                new Country { Name = "Philippines", Icon = "PH" },
                new Country { Name = "Puerto Rico", Icon = "PR" },
                new Country { Name = "Rwanda", Icon = "RW" },
                new Country { Name = "Samoa", Icon = "WS" },
                new Country { Name = "San Marino", Icon = "SM" },
                new Country { Name = "Seychelles", Icon = "SC" },
                new Country { Name = "Sierra Leone", Icon = "SL" },
                new Country { Name = "Somalia", Icon = "SO" },
                new Country { Name = "South Africa", Icon = "ZA" },
                new Country { Name = "South Sudan", Icon = "SS" },
                new Country { Name = "Spain", Icon = "ES" },
                new Country { Name = "Sri Lanka", Icon = "LK" },
                new Country { Name = "Sudan", Icon = "SD" },
                new Country { Name = "Suriname", Icon = "SR" },
                new Country { Name = "Tanzania", Icon = "TZ" },
                new Country { Name = "Thailand", Icon = "TH" },
                new Country { Name = "Togo", Icon = "TG" },
                new Country { Name = "Turkmenistan", Icon = "TM" },
                new Country { Name = "Uganda", Icon = "UG" },
                new Country { Name = "Uruguay", Icon = "UY" },
                new Country { Name = "Uzbekistan", Icon = "UZ" },
                new Country { Name = "Venezuela", Icon = "VE" },
                new Country { Name = "Vietnam", Icon = "VN" },
                new Country { Name = "Virgin Islands (British)", Icon = "VG" },
                new Country { Name = "Virgin Islands (U.S.)", Icon = "VI" },
                new Country { Name = "Yemen", Icon = "YE" },
                new Country { Name = "Zambia", Icon = "ZM" },
                new Country { Name = "Zimbabwe", Icon = "ZW" }
        };
    }
}
